export {
  ANNOTATION_PANEL_WIDTH_KEY,
  DEFAULT_ANNOTATION_PANEL_WIDTH,
  MAX_ANNOTATION_PANEL_WIDTH,
  MIN_ANNOTATION_PANEL_WIDTH,
  TOC_RAIL_WIDTH,
  clampAnnotationPanelWidth,
  readerRightPanelWidth,
} from "./panelLayout";
